version: '3.7'

services:
  backend:
    build: ./docker/backend/
    image: ${PROJECT}:backend-0.1
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    depends_on:
      - mongo
    ports:
      - ${BACKEND_EXTERNAL_PORT}:${BACKEND_PORT}
    working_dir: /src
    volumes:
      - ./backend:/src
    # command: ["npm", "i"]
    command: ["npm", "run", "dev"]

  mongo:
    build:
      context: ./docker/mongo/
      dockerfile: Dockerfile
      args:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_NAME=${MONGO_NAME}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
    image: ${PROJECT}:mongo-0-1
    restart: always
    volumes:
      - ./docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}